const $=s=>document.querySelector(s);const app=$('#app');
const seed=[
{id:1,emoji:'🎮',title:'PlayStation 5 Slim',price:349,loc:'Nürnberg · 3 km',cat:'Elektronik'},
{id:2,emoji:'👟',title:'Nike Air Max',price:65,loc:'Fürth · 7 km',cat:'Mode'},
{id:3,emoji:'🚲',title:'City Fahrrad',price:190,loc:'Nürnberg · 5 km',cat:'Fahrrad'},
{id:4,emoji:'☕',title:'Kaffeemaschine',price:45,loc:'Stein · 11 km',cat:'Haushalt'},
{id:5,emoji:'📱',title:'Smartphone 128 GB',price:220,loc:'Nürnberg · 2 km',cat:'Elektronik'},
{id:6,emoji:'🪑',title:'Vintage Stuhl',price:35,loc:'Erlangen · 18 km',cat:'Möbel'}];
let items=JSON.parse(localStorage.getItem('items')||'null')||seed;let fav=JSON.parse(localStorage.getItem('fav')||'[]');let listing={};
function save(){localStorage.setItem('items',JSON.stringify(items));localStorage.setItem('fav',JSON.stringify(fav));}
function header(){return `<div class="top"><div class="brand">FLOH<b>KI</b></div><div class="avatar">F</div></div>`}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1700)}
function card(i){return `<div class="card" onclick="openItem(${i.id})"><div class="thumb">${i.emoji||'📦'}</div><div class="body"><button class="heart" onclick="event.stopPropagation();toggleFav(${i.id})">${fav.includes(i.id)?'♥':'♡'}</button><div class="price">${i.price} €</div><div class="title">${i.title}</div><div class="meta">${i.loc||'In deiner Nähe'}</div></div></div>`}
function renderHome(q=''){let list=items.filter(i=>i.title.toLowerCase().includes(q.toLowerCase()));app.innerHTML=`<main class="page">${header()}<div class="hero"><span class="ai">✦ KI-Flohmarkt</span><h1>Verkaufen war noch nie so einfach.</h1><p>Foto machen. FLOHKI erstellt Preis, Titel und Beschreibung.</p><button class="primary" onclick="go('sell')">📸 Jetzt verkaufen</button></div><input class="search" id="search" placeholder="🔎 Was suchst du?" value="${q}"><div class="chips"><span class="chip">Alles</span><span class="chip">Elektronik</span><span class="chip">Mode</span><span class="chip">Fahrrad</span><span class="chip">Möbel</span></div><h2 class="section">In deiner Nähe</h2><div class="grid">${list.map(card).join('')}</div></main>`;$('#search').oninput=e=>renderHome(e.target.value)}
function renderFav(){let list=items.filter(i=>fav.includes(i.id));app.innerHTML=`<main class="page">${header()}<h1>Favoriten</h1>${list.length?`<div class="grid">${list.map(card).join('')}</div>`:`<div class="empty">♡<h3>Noch keine Favoriten</h3><p>Tippe bei einem Artikel auf das Herz.</p></div>`}</main>`}
function renderSell(){app.innerHTML=`<main class="page">${header()}<h1>Artikel verkaufen</h1><div class="box upload"><div style="font-size:50px">📸</div><h2>Mach ein Foto</h2><p class="muted">FLOHKI bereitet daraus automatisch deine Anzeige vor.</p><input id="photo" type="file" accept="image/*" capture="environment"><button class="primary" onclick="analyze()">✦ Mit FLOHKI analysieren</button></div><div class="legal">Die Analyse in Version 1.0 läuft lokal als intelligente Verkaufshilfe. Bitte prüfe Angaben und Preis vor dem Veröffentlichen.</div></main>`}
function analyze(){let f=$('#photo').files[0];listing={title:'Gebrauchter Artikel',emoji:'📦',cat:'Sonstiges',condition:'Gut',base:45};if(f){let n=f.name.toLowerCase();if(n.includes('shoe')||n.includes('nike'))listing={title:'Sneaker / Sportschuhe',emoji:'👟',cat:'Mode',condition:'Gut',base:65};if(n.includes('phone')||n.includes('iphone'))listing={title:'Smartphone',emoji:'📱',cat:'Elektronik',condition:'Gut',base:220};}renderAnalysis()}
function renderAnalysis(){let b=listing.base;app.innerHTML=`<main class="page">${header()}<span class="ai">✦ FLOHKI Analyse</span><h1>Artikel erkannt</h1><div class="box row"><div style="font-size:52px">${listing.emoji}</div><div><b>${listing.title}</b><div class="muted">${listing.cat} · Zustand: ${listing.condition}</div></div></div><h2 class="section">Preisvorschlag</h2><div class="pricing"><div class="priceopt" onclick="pickPrice(${Math.round(b*.82)},this)"><small>Schnell</small><br><b>${Math.round(b*.82)} €</b></div><div class="priceopt active" onclick="pickPrice(${b},this)"><small>Marktpreis</small><br><b>${b} €</b></div><div class="priceopt" onclick="pickPrice(${Math.round(b*1.18)},this)"><small>Geduldig</small><br><b>${Math.round(b*1.18)} €</b></div></div><button class="primary" onclick="editListing()">Anzeige fertigstellen →</button><button class="secondary" onclick="go('sell')">Neu fotografieren</button></main>`;listing.price=b}
function pickPrice(p,el){listing.price=p;document.querySelectorAll('.priceopt').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function editListing(){app.innerHTML=`<main class="page">${header()}<span class="ai">✦ KI-Entwurf</span><h1>Anzeige erstellen</h1><div class="label">Titel</div><input id="ltitle" class="field" value="${listing.title}"><div class="label">Preis</div><input id="lprice" class="field" type="number" value="${listing.price}"><div class="label">Beschreibung</div><textarea id="ldesc" class="field" rows="6">Verkaufe ${listing.title}. Der Artikel ist gebraucht und in gutem Zustand. Privatverkauf. Bei Fragen gerne schreiben.</textarea><div class="label">Ort</div><input id="lloc" class="field" value="Nürnberg"><button class="primary" onclick="publish()">🚀 Anzeige veröffentlichen</button></main>`}
function publish(){let id=Date.now();items.unshift({id,emoji:listing.emoji,title:$('#ltitle').value||listing.title,price:Number($('#lprice').value)||listing.price,loc:($('#lloc').value||'Nürnberg')+' · Neu',cat:listing.cat});save();toast('Anzeige veröffentlicht ✓');setTimeout(()=>go('home'),400)}
function renderChat(){app.innerHTML=`<main class="page">${header()}<h1>Chat</h1><div class="box"><b>Max · PlayStation 5 Slim</b><div class="chatmsg">Hallo, ist die PS5 noch da?</div><div class="chatmsg mine">Ja, sie ist noch verfügbar 👍</div><div class="chatmsg">Würdest du 330 € machen?</div><div class="row"><input id="msg" class="field grow" placeholder="Nachricht schreiben"><button class="primary" style="width:auto" onclick="sendMsg()">Senden</button></div></div></main>`}
function sendMsg(){let v=$('#msg').value.trim();if(v){let d=document.createElement('div');d.className='chatmsg mine';d.textContent=v;$('#msg').parentElement.before(d);$('#msg').value=''}}
function renderProfile(){app.innerHTML=`<main class="page">${header()}<div class="box" style="text-align:center"><div class="avatar" style="margin:auto;width:70px;height:70px;font-size:27px">F</div><h2>FLOHKI Nutzer</h2><p class="muted">★★★★★ · Noch keine Bewertungen</p></div><div class="box"><div class="row"><b class="grow">Meine Anzeigen</b><span>${items.length-seed.length}</span></div></div><div class="box"><b>FLOHKI Pro</b><p class="muted">Mehr KI-Analysen, Statistiken und Boosts.</p><button class="secondary" onclick="toast('Pro kommt in einer späteren Version')">Mehr erfahren</button></div><div class="box"><b>Datenschutz & Rechtliches</b><p class="legal">FLOHKI 1.0 speichert Daten dieser lokalen Version ausschließlich auf deinem Gerät. Für einen öffentlichen Mehrnutzer-Marktplatz müssen vor dem Launch Backend, Datenschutzinformationen, Moderation und Nutzerkonten ergänzt werden.</p></div></main>`}
function openItem(id){let i=items.find(x=>x.id===id);app.innerHTML=`<main class="page">${header()}<div class="thumb" style="height:260px;border-radius:22px">${i.emoji}</div><h1>${i.title}</h1><div class="price" style="font-size:30px">${i.price} €</div><p class="muted">${i.loc}</p><div class="box"><b>Beschreibung</b><p>Gebrauchter Artikel in gutem Zustand. Bei Interesse einfach eine Nachricht senden.</p></div><button class="primary" onclick="go('chat')">✉ Nachricht senden</button><button class="secondary" onclick="toggleFav(${i.id});openItem(${i.id})">${fav.includes(i.id)?'♥ Aus Favoriten entfernen':'♡ Merken'}</button></main>`}
function toggleFav(id){fav=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];save();toast(fav.includes(id)?'Gespeichert ♥':'Entfernt')}
function go(p){history.pushState({p},'',`#${p}`);render(p)}function render(p){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));({home:renderHome,favorites:renderFav,sell:renderSell,chat:renderChat,profile:renderProfile}[p]||renderHome)()}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));window.onpopstate=e=>render((e.state&&e.state.p)||'home');render(location.hash.slice(1)||'home');
