name: FLOHKI Keystore erstellen

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Keystore erstellen
        run: |
          keytool -genkeypair \
            -keystore flohki-release.jks \
            -alias flohki \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "${{ secrets.FLOHKI_KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.FLOHKI_KEY_PASSWORD }}" \
            -dname "CN=FLOHKI, OU=FLOHKI, O=FLOHKI, L=Nuremberg, ST=Bavaria, C=DE"

      - name: Keystore speichern
        uses: actions/upload-artifact@v4
        with:
          name: FLOHKI-KEYSTORE
          path: flohki-release.jks
